version: '3.1'

services:
  app:
    container_name: springserver
    image: springserver
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Qasaqayj7
      - POSTGRES_USER=postgres
      - POSTGRES_DB=effective
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
